name: Deploy

on:
  workflow_dispatch:
  # Just run it

env:
  CARGO_TERM_COLOR: always
  DEPLOY_ALOWED_USERS: "${{ secrets.DEPLOY_ALOWED_USERS }}"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/infinity-swap/ic-dev-base:latest
      credentials:
        username: ${{ secrets.GH_PKG_TOKEN }}
        password: ${{ secrets.GH_PKG_LOGIN }}

    steps:
      - name: Just check
        run: |
          echo "Actor is ${{ github.actor }}"

      - name: So something
        run: |
          pwd
          ls -la

      - name: So something
        env:
          IC_IDENTITY: "${{ secrets.DEPLOY_IC_IDENTITY }}"
        run: |
          echo "$IC_DENTITY" > ~/ic-idenityt.pem
          dfx identity import deployer ./ic-idenityt.pem 
          dfx identity list

      - name: Echo actual deploy
        #!!! IMPORTANT !!!
        # This line here is because of SECURITY concerns
        # Do not remove it
        if: contains(fromJson(env.DEPLOY_ALOWED_USERS), github.actor)
        run: |
          echo "DEPLOYING TO THE IC"
      
      - name: So something
        run: |
          pwd
          ls -la
          ls -la ~
        
