name: Deploy Cloud Run

on:
  workflow_dispatch:
  # Just run it

env:
  CARGO_TERM_COLOR: always
  DEPLOY_ALOWED_USERS: ${{ secrets.DEPLOY_ALOWED_USERS }}

jobs:
  deploy:
    # if: contains(fromJson(env.DEPLOY_ALOWED_USERS), github.actor)
    uses: infinity-swap/ci-wf/.github/workflows/deploy-cloud-run.yml@main
    with:
      gcp_project: dfx-server
      gcp_image_uri: us-central1-docker.pkg.dev/dfx-server/dfx-containers/example-dev-image
      region: us-central1
      service: example-dev

    secrets:
      gcp_deploy_token: ${{ secrets.GCP_JSON_DEPLOY_TOKEN }}

