name: "Prepare release"

on:
  workflow_dispatch:

  push:
    tags:
      - 'v*'

jobs:
  build-test:
    uses: infinity-swap/ci-wf/.github/workflows/build-n-test.yml@main
    with:
      container-image: ghcr.io/infinity-swap/ic-dev-full:rust1.62-dfx0.11
      disable-cache: ${{ inputs.disable-cache == true }}
      test-script: dev/dfx.run.tests.sh
      skip-test: true
      #audit-allow-warnings: true
      output-artifact: artiract-hello

      # This is kinda tricky.
      # We must provide some script that will put everything for publishing in the .artifact directory
      artifact-script: |
        cargo update
        ./scripts/build-artifact.sh

    secrets:
      gh_token: ${{ secrets.GH_PKG_TOKEN }}
      gh_login: ${{ secrets.GH_PKG_LOGIN }}