name: "Bump package version"

on:
  workflow_dispatch:

  push:
    branches:    
      - 'main'  

jobs:
  versioning:
    uses: infinity-swap/ci-wf/.github/workflows/bump-version-tag.yml@mbranch

    secrets:
      gh_token: ${{ secrets.GH_PKG_TOKEN }}

